services:
  frontend:
    container_name: $PROJECT-frontend
    build:
      context: ./frontend
      dockerfile: resources/Dockerfile.dev
      args:
        NODE_VERSION: ${NODE_VERSION}
    command: npm run dev
    ports:
      - 5173:5173
    volumes:
      - ./frontend/src:/app/src
    depends_on:
      backend:
        condition: service_healthy

  backend:
    container_name: $PROJECT-backend
    build:
      context: ./backend
      dockerfile: resources/Dockerfile.dev
    command: cargo run
    ports:
      - 2525:2525
    volumes:
      - ./backend/src:/app/src
      - ./backend/Cargo.toml:/app/Cargo.toml
      - ./backend/Cargo.lock:/app/Cargo.lock
      - ./backend/migrations:/app/migrations
      - backend_target:/app/target
    environment:
      - DATABASE_URL=sqlite:///app/mailfang.db

volumes:
  backend_target:
